alias ls='ls -h --color=auto'
alias ll='ls -hla --color=auto'
alias ltr='ls -hlatr --color=auto' 
alias rm='rm -i'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
